# Generated by Django 5.0.2 on 2024-04-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_rename_name_user_username_alter_article_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='article',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
