# Generated by Django 5.0.2 on 2024-04-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_delete_user_article_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_id',
        ),
    ]
