# Generated by Django 5.0.2 on 2024-04-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_alter_article_options_alter_plan_from_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
